
services:

  db:
    image: "postgres:16-alpine"
    restart: always
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      bookstore_network:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5m1s
      timeout: 5s
      retries: 5

  db_migrations:
    build:
      context: .
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate"

    env_file:
      - ./.env.dev
    networks:
      - bookstore_network
    depends_on:
      db: 
        condition: service_healthy

  redis_db:
    image: "redis:alpine"
    ports:
      - "6382:6379"
    networks: 
      - bookstore_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 5s
    

  backend:
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
      - bookstore_network
    volumes:
      - .:/app  # Mount code for live development
    depends_on:
      db:
        condition: service_healthy
      db_migrations:
        condition: service_completed_successfully
      redis_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/v1/health-check/ || exit 1"]
      interval: 5m10s
      timeout: 10s
      retries: 3

    restart: always

 
networks:
  bookstore_network:

volumes:
  postgres_data:
  redis_data:
    external: false
