# Generated by Django 5.1 on 2024-11-16 12:02

from django.db import migrations

from booksvault.models import Category


def add_categories(apps, schema_editor):
    categories = [
        'Fiction',
        'Non-Fiction',
        'Science',
        'Biography',
        'Mystery',
        'Fantasy',
        'History',
        'Romance',
        'Horror',
        'Children'
    ]
    for category in categories:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('booksvault', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
